services:
  - type: web
    name: minecraft-server
    runtime: docker
    privileged: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "5000"
      - key: MC_RAM
        value: "300M"  # JVM Xmx cap: 300MB (Render free 512MB limit)
    healthCheckPath: /
    numInstances: 1
